name: Scraper

on:
  schedule:
    - cron: '0 8 * * *' # Daily Sweep
  workflow_dispatch:
    inputs:
      specific_item:
        description: 'Specific item to scrape immediately'
        required: false
        default: ''

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      
      # We pass the input to the script as an Environment Variable
      - name: Run Scraper
        env:
          SPECIFIC_ITEM: ${{ github.event.inputs.specific_item }}
        run: node scraper.js

      - name: Commit Data
        run: |
          git config --global user.name 'PriceBot'
          git config --global user.email 'bot@noreply.com'
          git pull # Pull latest changes to avoid conflicts
          git add prices.json
          git commit -m "Update prices" || exit 0
          git push
